use_frameworks!

target 'TFImage_Example' do
  pod 'TFImage', :path => '../'

  target 'TFImage_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
